### ISSUE TITLE
Python 3.5 compatibility

### ISSUE THREAD

**Issue by rhaarm** [smiley/steamapi#25]
Does the current state of the api support Python 3.5? I forked this and plan to make updates to possibly support async from PY35, if time permits!

**Comment by smiley** [comment]
Great idea! I thought to implement this with Requests' async capabilities, but couldn't find the time to keep working on it. (And then Python 3.5 was released)

There shouldn't be any compatibility issues. The package used to be incompatible with Python 3.x due to some backwards-incompatible changes in 3.x (see #16 & #18), but it should work now.

Async is awesome, but it shouldn't break compatibility with <3.5. If you can't work a single solution for 2.7 - 3.5, you can create a shim at [`_shims` in `core.py`](/smiley/steamapi/blob/master/steamapi/core.py#L598) for version-dependent behaviour.
