### ISSUE TITLE
PyPi support

### ISSUE THREAD

**Issue by indietyp** [smiley/steamapi#54]
I am suggesting to support the package through pypi, so installation as well as distribution is easier.

Currently installing this package otherwise is just unnecessary complicated.

The package could even be tagged as alpha and nicht production ready.

If requested I could modify the setup.py accordingly.

**Comment by smiley** [comment]
This reply is a year late but it kinda proves my point. This was a side project, and I've had more time & drive to work on it back then. Since, I've switched to a way more demanding job and have way less time for these projects I had. This doesn't mean it's entirely abandoned, and while it's still pretty basic and not as performant as I'd like it to be, it still isn't broken or buggy as far as I can tell.

That said, I don't feel confident putting it up publicly in PyPi as something you can just randomly install & use. GitHub discovery is fairly good and something a lot of people do before reinventing the wheel, just in case someone else did it first. If someone does that, they can see the package's state & alpha/beta notice, and act accordingly. So all in all, I'd like to keep it GitHub-only for those reasons.

Also, you can install it fairly easily with `pip` by using the `git` source:
```bash
pip install git+https://github.com/smiley/steamapi.git
```
The same URL can also be put in your `requirements.txt`:
```text
requests >= 2.20
somelibrary
git+https://github.com/smiley/steamapi.git
```
