### ISSUE TITLE
Question: Can I see if a user is playing a game in real-time?

### ISSUE THREAD

**Issue by Russell-Nathan** [smiley/steamapi#64]

**Comment by smiley** [comment]
Sort-of, after you init the library and get a reference to a user (see examples in the [README.md](/smiley/steamapi/tree/master/README.md#how-do-i-use-this)), `user.currently_playing` will tell you what they're playing right now (or `None` if they're not playing anything).

Note that this is cached because, when all of this was originally developed, the API was already lagging in info compared to profiles and there was no sense in repeatedly asking for info. So if you want to keep querying `user.currently_playing`, you'll need to [manually expire `_summary` and `currently_playing` from the cache](https://github.com/smiley/steamapi/blob/master/steamapi/decorators.py#L50). That note describes how the cache functions and how you can manually delete something from it.

**Comment by Russell-Nathan** [comment]
awesome thanks.
